<script setup lang="ts">
import {
  Plus, Edit, Trash2, X, AlertTriangle, Info, Eye, ArrowLeft,
  Search, Check, ChevronLeft, ChevronRight, Save, RefreshCw,
  Download, Upload, Ban, Star, Loader2, EyeOff, Lock, Unlock,
  ArrowRight, CheckCircle, XCircle, ShoppingCart, CreditCard,
  Landmark, Package, Users, FileText, Settings,
  Mail, Shield, LogOut, ExternalLink, Menu, ChevronDown,
  LayoutDashboard, ClipboardList, Ticket, Folder, User,
  Phone, Calendar, Clock, Heart, Home, MapPin, Building2,
  ShoppingBag, Palette, Ruler, Globe, Image, Camera,
  Tag, HelpCircle, List, ListOrdered, Link, Link2Off,
  RemoveFormatting, RotateCcw, Upload as UploadIcon,
  Table, CircleMinus, CirclePlus, Bug, Send, MessageCircle,
  Megaphone, Contact, TrendingUp, Receipt,
  Newspaper, Grid3x3, BadgeCheck, DollarSign,
  Truck, Pointer, AtSign,   Handshake, Film, Layers, Layout, ShieldCheck, Badge,
  type Component
} from '@lucide/vue'

const iconMap: Record<string, Component> = {
  add: Plus,
  edit: Edit,
  delete: Trash2,
  close: X,
  warning: AlertTriangle,
  info: Info,
  visibility: Eye,
  arrow_back: ArrowLeft,
  search: Search,
  check: Check,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  save: Save,
  update: RefreshCw,
  refresh: RefreshCw,
  download: Download,
  upload: UploadIcon,
  block: Ban,
  star: Star,
  progress_activity: Loader2,
  edit_off: EyeOff,
  lock: Lock,
  lock_open: Unlock,
  arrow_forward: ArrowRight,
  check_circle: CheckCircle,
  cancel: XCircle,
  shopping_cart: ShoppingCart,
  credit_card: CreditCard,
  account_balance: Landmark,
  payments: DollarSign,
  point_of_sale: ShoppingCart,
  inventory_2: Package,
  group: Users,
  article: FileText,
  description: FileText,
  settings: Settings,
  mail: Mail,
  security: Shield,
  logout: LogOut,
  open_in_new: ExternalLink,
  menu: Menu,
  expand_more: ChevronDown,
  dashboard: LayoutDashboard,
  receipt_long: ClipboardList,
  confirmation_number: Ticket,
  category: Folder,
  person: User,
  phone: Phone,
  calendar_today: Calendar,
  history: Clock,
  favorite: Heart,
  home: Home,
  pin_drop: MapPin,
  location_city: Building2,
  shopping_bag: ShoppingBag,
  palette: Palette,
  straighten: Ruler,
  travel_explore: Globe,
  image: Image,
  photo_library: Camera,
  sell: Tag,
  help: HelpCircle,
  cloud_upload: UploadIcon,
  format_list_bulleted: List,
  format_list_numbered: ListOrdered,
  link: Link,
  link_off: Link2Off,
  format_clear: RemoveFormatting,
  restore: RotateCcw,
  table_rows: Table,
  remove: CircleMinus,
  add_circle: CirclePlus,
  remove_circle: CircleMinus,
  bug_report: Bug,
  send: Send,
  chat: MessageCircle,
  campaign: Megaphone,
  contacts: Contact,
  trending_up: TrendingUp,
  receipt: Receipt,
  newspaper: Newspaper,
  grid: Grid3x3,
  badge: Badge,
  verified: BadgeCheck,
  policy: ShieldCheck,
  movie: Film,
  new_releases: Layers,
  handshake: Handshake,
  call_to_action: Pointer,
  alternate_email: AtSign,
  local_shipping: Truck,
  settings_applications: Layout,
  people: Users,
  inventory: Package,
}

const props = withDefaults(defineProps<{
  icon: string
  size?: number
}>(), { size: 20 })

const iconComponent = iconMap[props.icon] || HelpCircle
</script>

<template>
  <component :is="iconComponent" :size="size" aria-hidden="true" />
</template>
